//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPBackup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPBackup.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © ultrashot 2012
        ///
        ///Special thanks to: 
        ///AsusMobile.ru team (AndrewSh, Barin, Feropont, lucifer3006, Vladimir1973), XDA-Developers team (CeesHeim, Football, Heathcliff74, HD2Owner, OndraSter, xboxmod and others), and Cotulla (DFT).
        ///
        ///This release is devoted to S.D..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About 
        ///Windows Phone Backup.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        public static string Alarms {
            get {
                return ResourceManager.GetString("Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is currently doing some work. Are you sure you really want to interrupt it?.
        /// </summary>
        public static string AppIsBusy {
            get {
                return ResourceManager.GetString("AppIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;OK&quot; once you finish installing all applications.
        ///Press &quot;Cancel&quot; to skip restoring application data..
        /// </summary>
        public static string ApplicationDataContinue {
            get {
                return ResourceManager.GetString("ApplicationDataContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications [long].
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up alarms....
        /// </summary>
        public static string BackingUpAlarms {
            get {
                return ResourceManager.GetString("BackingUpAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up applications....
        /// </summary>
        public static string BackingUpApplications {
            get {
                return ResourceManager.GetString("BackingUpApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up Bing Maps cache....
        /// </summary>
        public static string BackingUpBingMapsCache {
            get {
                return ResourceManager.GetString("BackingUpBingMapsCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up camera photo count....
        /// </summary>
        public static string BackingUpCameraPhotoCount {
            get {
                return ResourceManager.GetString("BackingUpCameraPhotoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up contacts....
        /// </summary>
        public static string BackingUpContacts {
            get {
                return ResourceManager.GetString("BackingUpContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up lockscreen timeout....
        /// </summary>
        public static string BackingUpLockscreenTimeout {
            get {
                return ResourceManager.GetString("BackingUpLockscreenTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up MMS....
        /// </summary>
        public static string BackingUpMMS {
            get {
                return ResourceManager.GetString("BackingUpMMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up &quot;My Documents&quot;....
        /// </summary>
        public static string BackingUpMyDocuments {
            get {
                return ResourceManager.GetString("BackingUpMyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up schedule....
        /// </summary>
        public static string BackingUpSchedule {
            get {
                return ResourceManager.GetString("BackingUpSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up SMS....
        /// </summary>
        public static string BackingUpSMS {
            get {
                return ResourceManager.GetString("BackingUpSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up keyboard dictionary....
        /// </summary>
        public static string BackingUpUserDictionary {
            get {
                return ResourceManager.GetString("BackingUpUserDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up WiFi networks....
        /// </summary>
        public static string BackingUpWifiNetworks {
            get {
                return ResourceManager.GetString("BackingUpWifiNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyway, don&apos;t forget to backup as often as possible to prevent data loss..
        /// </summary>
        public static string BackupCancelled {
            get {
                return ResourceManager.GetString("BackupCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now your data will be safe..
        /// </summary>
        public static string BackupCompletedText {
            get {
                return ResourceManager.GetString("BackupCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup device data.
        /// </summary>
        public static string BackupDeviceData {
            get {
                return ResourceManager.GetString("BackupDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup the most important data to easily migrate to another firmware..
        /// </summary>
        public static string BackupDeviceDataText {
            get {
                return ResourceManager.GetString("BackupDeviceDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is being created....
        /// </summary>
        public static string BackupIsBeingCreated {
            get {
                return ResourceManager.GetString("BackupIsBeingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is being restored.
        /// </summary>
        public static string BackupIsBeingRestored {
            get {
                return ResourceManager.GetString("BackupIsBeingRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait. Your data will be restored soon..
        /// </summary>
        public static string BackupRestorationText {
            get {
                return ResourceManager.GetString("BackupRestorationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Maps cache.
        /// </summary>
        public static string BingMapsCache {
            get {
                return ResourceManager.GetString("BingMapsCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string btnBackup {
            get {
                return ResourceManager.GetString("btnBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string btnRestore {
            get {
                return ResourceManager.GetString("btnRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera photo count.
        /// </summary>
        public static string CameraPhotoCount {
            get {
                return ResourceManager.GetString("CameraPhotoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel backup process?.
        /// </summary>
        public static string CancelBackupText {
            get {
                return ResourceManager.GetString("CancelBackupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel restore process? .
        /// </summary>
        public static string CancelRestoreText {
            get {
                return ResourceManager.GetString("CancelRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose backup file.
        /// </summary>
        public static string ChooseBackupFile {
            get {
                return ResourceManager.GetString("ChooseBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Mobile Device Center to connect to your device..
        /// </summary>
        public static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts, SMS, MMS, calendar.
        /// </summary>
        public static string ContactsSmsMmsSchedule {
            get {
                return ResourceManager.GetString("ContactsSmsMmsSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup.
        /// </summary>
        public static string CreatingBackup {
            get {
                return ResourceManager.GetString("CreatingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose items you want to backup..
        /// </summary>
        public static string CreatingBackupNote {
            get {
                return ResourceManager.GetString("CreatingBackupNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributive.
        /// </summary>
        public static string Distributive {
            get {
                return ResourceManager.GetString("Distributive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter backup file path or click &quot;Browse&quot; to find it easier..
        /// </summary>
        public static string EnterBackupPath {
            get {
                return ResourceManager.GetString("EnterBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comment.
        /// </summary>
        public static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be automatically added to archieve file..
        /// </summary>
        public static string EnterCommentText {
            get {
                return ResourceManager.GetString("EnterCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured during backup/restore process. Please, send these details to WPBackup developer:.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPBackup.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your backup:.
        /// </summary>
        public static string HereIsYourFile {
            get {
                return ResourceManager.GetString("HereIsYourFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard dictionary.
        /// </summary>
        public static string KeyboardDictionary {
            get {
                return ResourceManager.GetString("KeyboardDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockscreen timeout.
        /// </summary>
        public static string LockscreenTimeout {
            get {
                return ResourceManager.GetString("LockscreenTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMS.
        /// </summary>
        public static string MMS {
            get {
                return ResourceManager.GetString("MMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string MyDocuments {
            get {
                return ResourceManager.GetString("MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPBackup failed to start. There are two possible reasons:
        ///1) Windows Phone 7 SDK isn&apos;t installed. Get full one from microsoft.com, or install W.I.N.C.O. Mini SDK if application development capability isn&apos;t required.
        ///2) Windows Mobile Device Center isn&apos;t installed.
        ///.
        /// </summary>
        public static string NoSDK {
            get {
                return ResourceManager.GetString("NoSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose backup file.
        /// </summary>
        public static string OpenBackup {
            get {
                return ResourceManager.GetString("OpenBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, setup Live account first!.
        /// </summary>
        public static string PleaseSetupLiveAccount {
            get {
                return ResourceManager.GetString("PleaseSetupLiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for backup....
        /// </summary>
        public static string PreparingForBackup {
            get {
                return ResourceManager.GetString("PreparingForBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for restore....
        /// </summary>
        public static string PreparingForRestore {
            get {
                return ResourceManager.GetString("PreparingForRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing output file....
        /// </summary>
        public static string PreparingOutputFile {
            get {
                return ResourceManager.GetString("PreparingOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading contents....
        /// </summary>
        public static string ReadingContents {
            get {
                return ResourceManager.GetString("ReadingContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration.
        /// </summary>
        public static string Restoration {
            get {
                return ResourceManager.GetString("Restoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore:.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall applications.
        /// </summary>
        public static string RestoreApplicationDistributives {
            get {
                return ResourceManager.GetString("RestoreApplicationDistributives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore process was interrupted. There is a small chance of breaking useful information on your device. Be really careful..
        /// </summary>
        public static string RestoreCancelled {
            get {
                return ResourceManager.GetString("RestoreCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration completed. Please, reboot your phone as soon as possible to apply all changes reliably..
        /// </summary>
        public static string RestoreCompletedText {
            get {
                return ResourceManager.GetString("RestoreCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore device data from backup.
        /// </summary>
        public static string RestoreDeviceData {
            get {
                return ResourceManager.GetString("RestoreDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore previously saved data.
        /// </summary>
        public static string RestoreDeviceDataText {
            get {
                return ResourceManager.GetString("RestoreDeviceDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore following elements:.
        /// </summary>
        public static string RestoreFollowing {
            get {
                return ResourceManager.GetString("RestoreFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone was successfully restored.
        ///Let us know if you have any problem..
        /// </summary>
        public static string RestoreSuccessText {
            get {
                return ResourceManager.GetString("RestoreSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring alarms....
        /// </summary>
        public static string RestoringAlarms {
            get {
                return ResourceManager.GetString("RestoringAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring applications [stage 1]....
        /// </summary>
        public static string RestoringApplications1 {
            get {
                return ResourceManager.GetString("RestoringApplications1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring applications [stage 2]....
        /// </summary>
        public static string RestoringApplications2 {
            get {
                return ResourceManager.GetString("RestoringApplications2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring Bing Maps cache....
        /// </summary>
        public static string RestoringBingMapsCache {
            get {
                return ResourceManager.GetString("RestoringBingMapsCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring camera photo count....
        /// </summary>
        public static string RestoringCameraPhotoCount {
            get {
                return ResourceManager.GetString("RestoringCameraPhotoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring contacts....
        /// </summary>
        public static string RestoringContacts {
            get {
                return ResourceManager.GetString("RestoringContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring lockscreen timeout....
        /// </summary>
        public static string RestoringLockscreenTimeout {
            get {
                return ResourceManager.GetString("RestoringLockscreenTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring MMS....
        /// </summary>
        public static string RestoringMMS {
            get {
                return ResourceManager.GetString("RestoringMMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring &quot;My Documents&quot;....
        /// </summary>
        public static string RestoringMyDocuments {
            get {
                return ResourceManager.GetString("RestoringMyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring schedule....
        /// </summary>
        public static string RestoringSchedule {
            get {
                return ResourceManager.GetString("RestoringSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring SMS....
        /// </summary>
        public static string RestoringSMS {
            get {
                return ResourceManager.GetString("RestoringSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring keyboard dictionary....
        /// </summary>
        public static string RestoringUserDictionary {
            get {
                return ResourceManager.GetString("RestoringUserDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring WiFi networks....
        /// </summary>
        public static string RestoringWifiNetworks {
            get {
                return ResourceManager.GetString("RestoringWifiNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save:.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save backup as.
        /// </summary>
        public static string SaveBackupAs {
            get {
                return ResourceManager.GetString("SaveBackupAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving backup index....
        /// </summary>
        public static string SavingIndex {
            get {
                return ResourceManager.GetString("SavingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select applications.
        /// </summary>
        public static string SelectApps {
            get {
                return ResourceManager.GetString("SelectApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following applications will be saved:.
        /// </summary>
        public static string SelectAppsBackup {
            get {
                return ResourceManager.GetString("SelectAppsBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following applications will be restore:.
        /// </summary>
        public static string SelectAppsRestore {
            get {
                return ResourceManager.GetString("SelectAppsRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS, MMS, calendar.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string StateBackup {
            get {
                return ResourceManager.GetString("StateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup in progress.
        /// </summary>
        public static string StateBackupInProgress {
            get {
                return ResourceManager.GetString("StateBackupInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string StateRestore {
            get {
                return ResourceManager.GetString("StateRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore in progress.
        /// </summary>
        public static string StateRestoreInProgress {
            get {
                return ResourceManager.GetString("StateRestoreInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data backup tool for custom ROMs.
        /// </summary>
        public static string SubHeader {
            get {
                return ResourceManager.GetString("SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking backup....
        /// </summary>
        public static string UnpackingBackup {
            get {
                return ResourceManager.GetString("UnpackingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait a little. It will be ready in some minutes..
        /// </summary>
        public static string WaitALittle {
            get {
                return ResourceManager.GetString("WaitALittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        public static string WhatDoYouWantToDo {
            get {
                return ResourceManager.GetString("WhatDoYouWantToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi networks.
        /// </summary>
        public static string WifiNetworks {
            get {
                return ResourceManager.GetString("WifiNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPBackup files.
        /// </summary>
        public static string WPBackupFiles {
            get {
                return ResourceManager.GetString("WPBackupFiles", resourceCulture);
            }
        }
    }
}
